version: 2
jobs:
  full_test:
    docker:
      - image: arthurphilippe/epitech-c-cpp-plain
    steps:
      - checkout
      - run:
          name: Build Project
          command: make -j 4
      - run:
          name: Build Unit Tests Suites
          command: make tests -j 4
      - run:
          name: Tidy up
          command: make clean
      - run:
          name: Unit Tests Execution
          command: ./unit_tests.out
      - run:
          name: Functional Tests Execution
          command: ./tests/functionals_tests.sh
      - run:
          name: Code Coverage - Processing
          command: ./tests/coverage.sh
      - run:
          name: Code Coverage - Output
          command: cat coverage.log

  build_clang:
    docker:
      - image: arthurphilippe/clang
    steps:
      - checkout
      - run:
          name: Build Project Using clang
          command: make CXX=clang++ CPPFLAGS=-W\ -Wextra\ -Wall\ -Werror\ -Iinclude/\ -std=c++17 -j 4

  epitest:
    docker:
      - image: epitechcontent/epitest-docker
    steps:
      - checkout
      - run:
          name: Build Project
          command: make -j 4
      - run:
          name: Build Unit Tests Suites
          command: make tests -j 4
      - run:
          name: Tidy up
          command: make clean
      - run:
          name: Unit Tests Execution
          command: ./unit_tests.out
      - run:
          name: Functional Tests Execution
          command: ./tests/functionals_tests.sh

workflows:
  version: 2
  commit:
    jobs:
      - full_test
      - build_clang
  planned:
    triggers:
      - schedule:
          cron: "0 21 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - epitest
